name: Build and Deploy to GKE

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  GCR_REGION: ${{ vars.GCR_REGION }}

jobs:
  build-and-deploy:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Authentication
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ env.PROJECT_ID }}

    # Enable required APIs
    - name: Enable APIs
      run: |
        gcloud services enable containerregistry.googleapis.com
        gcloud services enable artifactregistry.googleapis.com

    # Configure docker to use gcloud as a credential helper
    - name: Docker auth configure
      run: |
        gcloud auth configure-docker asia.gcr.io --quiet

    # Build the Docker image
    - name: Build
      run: |
        docker build . \
          -t "${{ env.GCR_REGION }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" \
          -t "${{ env.GCR_REGION }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest"
      
    # Push the Docker image to Google Container Registry
    - name: Push
      run: |
        docker push "${{ env.GCR_REGION }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        docker push "${{ env.GCR_REGION }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest"